//
//  Workspace.swift
//  AniLanguageAppManifests
//
//  Created by 김용우 on 2023/11/05.
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: projectName + "Apps",
    projects: [
        "Projects/**"
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled,
        lastXcodeUpgradeCheck: Version(0, 0, 1),
        renderMarkdownReadme: true
    )
)
