//
//  Workspace.swift
//  AniLanguageAppManifests
//
//  Created by 김용우 on 2023/11/05.
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: projectName + "App",
    projects: [
        "App/CCRecorderApp/**",
        "Module/CommonLayer/**",
        "Module/DataLayer/**",
        "Module/DomainLayer/**",
        "Module/PresentationLayer/**"
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled,
        lastXcodeUpgradeCheck: Version(0, 0, 1),
        renderMarkdownReadme: true
    )
)
